### ISSUE TITLE
3 Single Machine Models (Deterministic)

### ISSUE THREAD

**Issue by Bancie** [S-ROLL/notebook.maths#304]
## Tasks:
- [ ] 3.1 The Total Weighted Completion Time
- [ ] 3.2 The Maximum Lateness
- [ ] 3.3 The Number of Tardy Jobs
- [ ] 3.4 TheTotalTardiness-DynamicProgramming
- [ ] 3.5 The Total Tardiness - An Approximation Scheme
- [ ] 3.6 The Total Weighted Tardiness
- [ ] 3.7 Discussion
