### ISSUE TITLE
Bài tập C/C++

### ISSUE THREAD

**Issue by Bancie** [S-ROLL/notebook.maths#320]
[PDF](https://www.icloud.com/iclouddrive/09cjMettSPcOeSM34dZh18VMw#Practice_content_Programming_techniques)
## Tasks:
- [x] S-ROLL/notebook.code#12
- [ ] S-ROLL/notebook.maths#319
- [x] S-ROLL/notebook.code#13
- [ ] S-ROLL/notebook.maths#318
- [ ] S-ROLL/notebook.maths#317
- [ ] S-ROLL/notebook.maths#316
- [ ] S-ROLL/notebook.maths#315
- [ ] S-ROLL/notebook.maths#314
