### ISSUE TITLE
Lý thuyết C/C++

### ISSUE THREAD

**Issue by Bancie** [S-ROLL/notebook.maths#321]
[Notebook](https://github.com/S-ROLL/notebook.code/blob/main/C-C++/notebook/nbcpp.ipynb)
## Tasks:
- [x] S-ROLL/notebook.code#5
- [x] S-ROLL/notebook.code#6
- [ ] S-ROLL/notebook.code#7
- [x] S-ROLL/notebook.code#8
- [ ] S-ROLL/notebook.code#9
- [x] S-ROLL/notebook.code#10
- [ ] S-ROLL/notebook.code#11
